# Label definitions for EndBug/label-sync
# This file is the source of truth for repository labels.
# Edit this file and push to main to sync labels automatically.

# ── Agent control ──
- name: "agent:claude"
  color: "0e8a16"
  description: "Assigned to Claude agent"
- name: "agent:copilot"
  color: "5319e7"
  description: "Assigned to Copilot or human"
- name: "agent:codex"
  color: "d93f0b"
  description: "Assigned to Codex agent"
- name: "agent:ready"
  color: "0e8a16"
  description: "Ready for agent pickup"
- name: "agent:queued"
  color: "fbca04"
  description: "Queued for agent processing"
- name: "agent:blocked"
  color: "b60205"
  description: "Blocked — needs human intervention"
- name: "agent:no-auto"
  color: "e4e669"
  description: "Do not auto-assign to agents"
- name: "agent-consolidation"
  color: "1d76db"
  description: "Consolidate agent instruction files into AGENTS.md"

# ── Type ──
- name: "bug"
  color: "d73a4a"
  description: "Something isn't working"
- name: "enhancement"
  color: "a2eeef"
  description: "New feature or request"
- name: "documentation"
  color: "0075ca"
  description: "Improvements or additions to documentation"
- name: "chore"
  color: "fef2c0"
  description: "Maintenance and housekeeping"
- name: "question"
  color: "d876e3"
  description: "Further information is requested"

# ── Priority ──
- name: "priority:critical"
  color: "b60205"
  description: "Must be resolved immediately"
- name: "priority:high"
  color: "d93f0b"
  description: "Important — resolve soon"
- name: "priority:medium"
  color: "fbca04"
  description: "Normal priority"
- name: "priority:low"
  color: "0e8a16"
  description: "Nice to have"

# ── Status ──
- name: "needs-triage"
  color: "ededed"
  description: "Needs initial assessment"
- name: "wontfix"
  color: "ffffff"
  description: "This will not be worked on"
- name: "duplicate"
  color: "cfd3d7"
  description: "This issue or pull request already exists"
- name: "good first issue"
  color: "7057ff"
  description: "Good for newcomers"
- name: "help wanted"
  color: "008672"
  description: "Extra attention is needed"
